### ISSUE TITLE
Lage milestones til hver uke 104/114

### ISSUE THREAD

**Issue by CarstenOst** [CarstenOst/Sarra_4B#34]
Tenker vi kan lage en milestone og linke issues til de, på denne måten slipper vi gantskjema og har all oversikt i github

- [ ] Laget milestones/milepæler ut semesteret

**Comment by StokkenLudvig** [comment]
To innspill:
1. Høres lurt ut å ha alt samla, dermed er milstones pr. uke et godt alternativ.
2. Gantt-skjema virker til å være en ganske utbredt mal for prosjektstyring, uavhengig av bransje. Jeg tenker derfor det er god læring for vår del å faktisk ta i bruk et Gantt-skjema for å erfare hvordan det fungerer. Så til senere kan vi si at Gantt-skjema, jada det kjenner jeg godt til :)

**Comment by StokkenLudvig** [comment]
Amalie har laget Gantt-skjema i doc. Avslutter derfor denne.
