### ISSUE TITLE
Settings.html

### ISSUE THREAD

**Issue by CarstenOst** [CarstenOst/Sarra_4B#38]
Fix myFriends icon being 45px instead of 35px in setting.html

**Comment by StokkenLudvig** [comment]
Friends icon are already 45px, not 35 px in document settings.html.
But in sarraDesign it's still 35px. Did you mean fix in sarraDesign? @CarstenOst

**Comment by CarstenOst** [comment]
Nope, in settings.html

**Comment by CarstenOst** [comment]
@StokkenLudvig 
Issue is here:
<img src="icon/friends_icon.png" alt="friends" height="45">

<img src="icon/friends_icon.png" alt="friends" height="35">
Correct version should be:  -----------------------------> ^^

**Comment by StokkenLudvig** [comment]
done
