### ISSUE TITLE
Helping/describing text on icons

### ISSUE THREAD

**Issue by CarstenOst** [CarstenOst/Sarra_4B#39]
Make text underneath icons which describe the icon

- [x] do this on all html pages

**Comment by StokkenLudvig** [comment]
Done on all but "settings.html".
And need to make text put center underneath icon.

**Comment by StokkenLudvig** [comment]
You closed this one.
But the text is still not center underneath icons.
We agree that's okay or should be fixed?

I fix the last on "settings.html" now.
@CarstenOst

**Comment by StokkenLudvig** [comment]
"settings.html" was already up to date. The all pages are done.
Only thing now is center both icon and text.
