### ISSUE TITLE
Create My Events page without choosen events, a "Empty state" - page

### ISSUE THREAD

**Issue by StokkenLudvig** [CarstenOst/Sarra_4B#51]
In the deliverable its asked for three different states. We have two ready, loading and error. This can be the third, if not the full page goes for being the "Ideal page". Then we already have three different states.

**Comment by CarstenOst** [comment]
I understood it as the full page is the "ideal page", but adding a blank page is pretty easy, and little time consuming. Can't possibly hurt imo

**Comment by StokkenLudvig** [comment]
Agree. On it now.

**Comment by StokkenLudvig** [comment]
Done, sent pull request.
